### ISSUE TITLE
Finpension: Transaction report was adjusted

### ISSUE THREAD

**Issue by mrsamse** [gregorias/hledupt#1]
Hello, Sam from finpension here!

We have just adapted our transaction report and have added an extra column: 
You can now find the ISIN number after the asset name.

Maybe you want to adjust your parser accordingly?

Keep up the good work!
Sam

**Comment by gregorias** [comment]
Awesome, thank you so much!

I've updated the parser in https://github.com/gregorias/hledupt/commit/362cf0ec8b1210dbb72c5eaf33ab95a58a14f093.
